services:
    # Database Service
    postgres:
        image: postgres:15-alpine
        container_name: itunes-search-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: itunes_search
            POSTGRES_USER: itunes_user
            POSTGRES_PASSWORD: itunes_password
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-db:/docker-entrypoint-initdb.d
        networks:
            - itunes-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U itunes_user -d itunes_search']
            interval: 10s
            timeout: 5s
            retries: 5

    # Database Admin Interface
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: itunes-search-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - itunes-network
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local

networks:
    itunes-network:
        driver: bridge
